apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctechnologies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abctechnologies
  template:
    metadata:
      labels:
        app: abctechnologies
    spec:
      containers:
        - name: abctechnologies
          image: venkatesansg111/abctechnologies:latest
          ports:
            - containerPort: 8080